apiVersion: confluent.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: confluent/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    availability: SINGLE_ZONE
    basic:
    - {}
    cloud: AWS
    displayName: basic_kafka_cluster
    environment:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: development
    region: us-east-2

---

apiVersion: confluent.crossplane.io/v1alpha1
kind: Environment
metadata:
  annotations:
    meta.upbound.io/example-id: confluent/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: development
  name: development
spec:
  forProvider:
    displayName: Development
