apiVersion: confluent.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: confluent/v1alpha1/serviceaccount
  labels:
    testing.upbound.io/example-name: example-sa
  name: example-sa
spec:
  forProvider:
    description: Service Account for orders app
    displayName: orders-app-sa
