// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ConnectorEnvironmentInitParameters struct {

	// The ID of the Environment that the connector belongs to, for example, env-abc123.
	// The unique identifier for the environment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ConnectorEnvironmentObservation struct {

	// The ID of the Environment that the connector belongs to, for example, env-abc123.
	// The unique identifier for the environment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ConnectorEnvironmentParameters struct {

	// The ID of the Environment that the connector belongs to, for example, env-abc123.
	// The unique identifier for the environment.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type ConnectorInitParameters struct {

	// Block for custom nonsensitive configuration properties that are not labelled with "Type: password" under "Configuration Properties" section in the docs:
	// The nonsensitive configuration settings to set (e.g., `"time.interval" = "DAILY"`).
	ConfigNonsensitive map[string]*string `json:"configNonsensitive,omitempty" tf:"config_nonsensitive,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	Environment []ConnectorEnvironmentInitParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// supports the following:
	KafkaCluster []KafkaClusterInitParameters `json:"kafkaCluster,omitempty" tf:"kafka_cluster,omitempty"`

	// supports the following:
	// Connector partitions with offsets
	Offsets []OffsetsInitParameters `json:"offsets,omitempty" tf:"offsets,omitempty"`

	// > "PAUSED") and resuming ("PAUSED" -> "RUNNING") a connector is supported via an update operation.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type ConnectorObservation struct {

	// Block for custom nonsensitive configuration properties that are not labelled with "Type: password" under "Configuration Properties" section in the docs:
	// The nonsensitive configuration settings to set (e.g., `"time.interval" = "DAILY"`).
	ConfigNonsensitive map[string]*string `json:"configNonsensitive,omitempty" tf:"config_nonsensitive,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	Environment []ConnectorEnvironmentObservation `json:"environment,omitempty" tf:"environment,omitempty"`

	// The ID of the Environment that the connector belongs to, for example, env-abc123.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// supports the following:
	KafkaCluster []KafkaClusterObservation `json:"kafkaCluster,omitempty" tf:"kafka_cluster,omitempty"`

	// supports the following:
	// Connector partitions with offsets
	Offsets []OffsetsObservation `json:"offsets,omitempty" tf:"offsets,omitempty"`

	// > "PAUSED") and resuming ("PAUSED" -> "RUNNING") a connector is supported via an update operation.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type ConnectorParameters struct {

	// Block for custom nonsensitive configuration properties that are not labelled with "Type: password" under "Configuration Properties" section in the docs:
	// The nonsensitive configuration settings to set (e.g., `"time.interval" = "DAILY"`).
	// +kubebuilder:validation:Optional
	ConfigNonsensitive map[string]*string `json:"configNonsensitive,omitempty" tf:"config_nonsensitive,omitempty"`

	// Block for custom sensitive configuration properties that are labelled with "Type: password" under "Configuration Properties" section in the docs:
	// The sensitive configuration settings to set (e.g., `"gcs.credentials.config" = "**REDACTED***"`). Should not be set for an import operation.
	// +kubebuilder:validation:Optional
	ConfigSensitiveSecretRef *v1.SecretReference `json:"configSensitiveSecretRef,omitempty" tf:"-"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	// +kubebuilder:validation:Optional
	Environment []ConnectorEnvironmentParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// supports the following:
	// +kubebuilder:validation:Optional
	KafkaCluster []KafkaClusterParameters `json:"kafkaCluster,omitempty" tf:"kafka_cluster,omitempty"`

	// supports the following:
	// Connector partitions with offsets
	// +kubebuilder:validation:Optional
	Offsets []OffsetsParameters `json:"offsets,omitempty" tf:"offsets,omitempty"`

	// > "PAUSED") and resuming ("PAUSED" -> "RUNNING") a connector is supported via an update operation.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type KafkaClusterInitParameters struct {

	// The ID of the Environment that the connector belongs to, for example, env-abc123.
	// The Kafka cluster ID (e.g., `lkc-12345`).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type KafkaClusterObservation struct {

	// The ID of the Environment that the connector belongs to, for example, env-abc123.
	// The Kafka cluster ID (e.g., `lkc-12345`).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type KafkaClusterParameters struct {

	// The ID of the Environment that the connector belongs to, for example, env-abc123.
	// The Kafka cluster ID (e.g., `lkc-12345`).
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type OffsetsInitParameters struct {

	// Block with offset information that supports different keys depending on the connector type. For sink connectors, use kafka_offset. For source connectors, the applicable keys differ by kind—refer to the Source connectors page for the full list of supported keys. Alternatively, use the Manage custom offsets section on the homepage of the target source connector.
	// Connector offsets information for the partition.
	Offset map[string]*string `json:"offset,omitempty" tf:"offset,omitempty"`

	// Block with partition information that supports different keys depending on the connector type. For sink connectors, use kafka_partition and kafka_topic. For source connectors, the applicable keys differ by kind—refer to the Source connectors page for the full list of supported keys.
	// Connector partitions information.
	Partition map[string]*string `json:"partition,omitempty" tf:"partition,omitempty"`
}

type OffsetsObservation struct {

	// Block with offset information that supports different keys depending on the connector type. For sink connectors, use kafka_offset. For source connectors, the applicable keys differ by kind—refer to the Source connectors page for the full list of supported keys. Alternatively, use the Manage custom offsets section on the homepage of the target source connector.
	// Connector offsets information for the partition.
	Offset map[string]*string `json:"offset,omitempty" tf:"offset,omitempty"`

	// Block with partition information that supports different keys depending on the connector type. For sink connectors, use kafka_partition and kafka_topic. For source connectors, the applicable keys differ by kind—refer to the Source connectors page for the full list of supported keys.
	// Connector partitions information.
	Partition map[string]*string `json:"partition,omitempty" tf:"partition,omitempty"`
}

type OffsetsParameters struct {

	// Block with offset information that supports different keys depending on the connector type. For sink connectors, use kafka_offset. For source connectors, the applicable keys differ by kind—refer to the Source connectors page for the full list of supported keys. Alternatively, use the Manage custom offsets section on the homepage of the target source connector.
	// Connector offsets information for the partition.
	// +kubebuilder:validation:Optional
	Offset map[string]*string `json:"offset" tf:"offset,omitempty"`

	// Block with partition information that supports different keys depending on the connector type. For sink connectors, use kafka_partition and kafka_topic. For source connectors, the applicable keys differ by kind—refer to the Source connectors page for the full list of supported keys.
	// Connector partitions information.
	// +kubebuilder:validation:Optional
	Partition map[string]*string `json:"partition" tf:"partition,omitempty"`
}

// ConnectorSpec defines the desired state of Connector
type ConnectorSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ConnectorParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConnectorInitParameters `json:"initProvider,omitempty"`
}

// ConnectorStatus defines the observed state of Connector.
type ConnectorStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ConnectorObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Connector is the Schema for the Connectors API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,confluent}
type Connector struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.configNonsensitive) || (has(self.initProvider) && has(self.initProvider.configNonsensitive))",message="spec.forProvider.configNonsensitive is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.environment) || (has(self.initProvider) && has(self.initProvider.environment))",message="spec.forProvider.environment is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.kafkaCluster) || (has(self.initProvider) && has(self.initProvider.kafkaCluster))",message="spec.forProvider.kafkaCluster is a required parameter"
	Spec   ConnectorSpec   `json:"spec"`
	Status ConnectorStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConnectorList contains a list of Connectors
type ConnectorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Connector `json:"items"`
}

// Repository type metadata.
var (
	Connector_Kind             = "Connector"
	Connector_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Connector_Kind}.String()
	Connector_KindAPIVersion   = Connector_Kind + "." + CRDGroupVersion.String()
	Connector_GroupVersionKind = CRDGroupVersion.WithKind(Connector_Kind)
)

func init() {
	SchemeBuilder.Register(&Connector{}, &ConnectorList{})
}
