// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type EnvironmentInitParameters_2 struct {

	// A human-readable name for the Environment. Start and end the name with alphanumeric characters, for example, "Development". The name can contain hyphens and underscores.
	// A human-readable name for the Environment.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The stream governance configuration for the Environment. The block supports the following arguments:
	// Stream Governance configurations for the environment
	StreamGovernance []StreamGovernanceInitParameters `json:"streamGovernance,omitempty" tf:"stream_governance,omitempty"`
}

type EnvironmentObservation_2 struct {

	// A human-readable name for the Environment. Start and end the name with alphanumeric characters, for example, "Development". The name can contain hyphens and underscores.
	// A human-readable name for the Environment.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The ID of the Environment, for example, env-abc123.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The Confluent Resource Name of the Environment, for example, crn://confluent.cloud/organization=1111aaaa-11aa-11aa-11aa-111111aaaaaa/environment=env-abc123.
	// The Confluent Resource Name of the Environment.
	ResourceName *string `json:"resourceName,omitempty" tf:"resource_name,omitempty"`

	// The stream governance configuration for the Environment. The block supports the following arguments:
	// Stream Governance configurations for the environment
	StreamGovernance []StreamGovernanceObservation `json:"streamGovernance,omitempty" tf:"stream_governance,omitempty"`
}

type EnvironmentParameters_2 struct {

	// A human-readable name for the Environment. Start and end the name with alphanumeric characters, for example, "Development". The name can contain hyphens and underscores.
	// A human-readable name for the Environment.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The stream governance configuration for the Environment. The block supports the following arguments:
	// Stream Governance configurations for the environment
	// +kubebuilder:validation:Optional
	StreamGovernance []StreamGovernanceParameters `json:"streamGovernance,omitempty" tf:"stream_governance,omitempty"`
}

type StreamGovernanceInitParameters struct {

	// The stream governance package for the Environment. Accepted values are: ESSENTIALS and ADVANCED.
	// Stream Governance Package. 'ESSENTIALS' or 'ADVANCED'
	Package *string `json:"package,omitempty" tf:"package,omitempty"`
}

type StreamGovernanceObservation struct {

	// The stream governance package for the Environment. Accepted values are: ESSENTIALS and ADVANCED.
	// Stream Governance Package. 'ESSENTIALS' or 'ADVANCED'
	Package *string `json:"package,omitempty" tf:"package,omitempty"`
}

type StreamGovernanceParameters struct {

	// The stream governance package for the Environment. Accepted values are: ESSENTIALS and ADVANCED.
	// Stream Governance Package. 'ESSENTIALS' or 'ADVANCED'
	// +kubebuilder:validation:Optional
	Package *string `json:"package" tf:"package,omitempty"`
}

// EnvironmentSpec defines the desired state of Environment
type EnvironmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EnvironmentParameters_2 `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EnvironmentInitParameters_2 `json:"initProvider,omitempty"`
}

// EnvironmentStatus defines the observed state of Environment.
type EnvironmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EnvironmentObservation_2 `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Environment is the Schema for the Environments API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,confluent}
type Environment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	Spec   EnvironmentSpec   `json:"spec"`
	Status EnvironmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EnvironmentList contains a list of Environments
type EnvironmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Environment `json:"items"`
}

// Repository type metadata.
var (
	Environment_Kind             = "Environment"
	Environment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Environment_Kind}.String()
	Environment_KindAPIVersion   = Environment_Kind + "." + CRDGroupVersion.String()
	Environment_GroupVersionKind = CRDGroupVersion.WithKind(Environment_Kind)
)

func init() {
	SchemeBuilder.Register(&Environment{}, &EnvironmentList{})
}
