/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RoleBindingObservation struct {

	// A CRN that specifies the scope and resource patterns necessary for the role to bind.
	CrnPattern *string `json:"crnPattern,omitempty" tf:"crn_pattern,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The principal User to bind the role to.
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// The name of the role to bind to the principal.
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`
}

type RoleBindingParameters struct {

	// A CRN that specifies the scope and resource patterns necessary for the role to bind.
	// +kubebuilder:validation:Optional
	CrnPattern *string `json:"crnPattern,omitempty" tf:"crn_pattern,omitempty"`

	// The principal User to bind the role to.
	// +kubebuilder:validation:Optional
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// The name of the role to bind to the principal.
	// +kubebuilder:validation:Optional
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`
}

// RoleBindingSpec defines the desired state of RoleBinding
type RoleBindingSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RoleBindingParameters `json:"forProvider"`
}

// RoleBindingStatus defines the observed state of RoleBinding.
type RoleBindingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RoleBindingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// RoleBinding is the Schema for the RoleBindings API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,confluent}
type RoleBinding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.crnPattern)",message="crnPattern is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.principal)",message="principal is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.roleName)",message="roleName is a required parameter"
	Spec   RoleBindingSpec   `json:"spec"`
	Status RoleBindingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RoleBindingList contains a list of RoleBindings
type RoleBindingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RoleBinding `json:"items"`
}

// Repository type metadata.
var (
	RoleBinding_Kind             = "RoleBinding"
	RoleBinding_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RoleBinding_Kind}.String()
	RoleBinding_KindAPIVersion   = RoleBinding_Kind + "." + CRDGroupVersion.String()
	RoleBinding_GroupVersionKind = CRDGroupVersion.WithKind(RoleBinding_Kind)
)

func init() {
	SchemeBuilder.Register(&RoleBinding{}, &RoleBindingList{})
}
