apiVersion: confluent.crossplane.io/v1alpha1
kind: KafkaACL
metadata:
  name: kafka-acl-confluent-cloud
spec:
  deletionPolicy: Delete
  forProvider:
    host: '*'
    kafkaCluster:
      - id: ${data.confluent_kafka_cluster_id}
    operation: READ
    patternType: PREFIXED
    permission: ALLOW
    principal: ${data.confluent_principal}
    resourceName: test-
    resourceType: TOPIC
  providerConfigRef:
    name: default
