apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-confluent
spec:
   package: "eureka-docker-prod.common.repositories.cloud.sap/nebulaworks/provider-confluent:0.0.1-local"
   packagePullSecrets:
     - name: eureka-registry