// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ArtifactInitParameters struct {

	// The artifact file for Flink Artifact.
	// The artifact file for Flink Artifact in JAR or ZIP format.
	ArtifactFile *string `json:"artifactFile,omitempty" tf:"artifact_file,omitempty"`

	// Java class or alias for the Flink Artifact as provided by developer.
	// Java class or alias for the Flink Artifact as provided by developer.
	Class *string `json:"class,omitempty" tf:"class,omitempty"`

	// The cloud service provider that runs the Flink Artifact.
	// Cloud provider where the Flink Artifact archive is uploaded.
	Cloud *string `json:"cloud,omitempty" tf:"cloud,omitempty"`

	// Archive format of the Flink Artifact. Accepted values are: JAR, ZIP.
	// Archive format of the Flink Artifact (JAR or ZIP).
	ContentFormat *string `json:"contentFormat,omitempty" tf:"content_format,omitempty"`

	// Description of the Flink Artifact.
	// Description of the Flink Artifact.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The unique name of the Flink Artifact per cloud, region, environment scope.
	// The unique name of the Flink Artifact per cloud, region, environment scope.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Documentation link of the Flink Artifact.
	// Documentation link of the Flink Artifact.
	DocumentationLink *string `json:"documentationLink,omitempty" tf:"documentation_link,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	Environment []EnvironmentInitParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// The cloud service provider region that hosts the Flink Artifact.
	// The Cloud provider region the Flink Artifact archive is uploaded.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Runtime language of the Flink Artifact as Python or Java. Defaults to Java.
	// Runtime language of the Flink Artifact as Python or JAVA. The default runtime language is JAVA. Defaults to `JAVA`.
	RuntimeLanguage *string `json:"runtimeLanguage,omitempty" tf:"runtime_language,omitempty"`
}

type ArtifactObservation struct {

	// The API Version of the schema version of the Flink Artifact Pool, for example, fa/v2.
	// The schema version of this representation of a resource.
	APIVersion *string `json:"apiVersion,omitempty" tf:"api_version,omitempty"`

	// The artifact file for Flink Artifact.
	// The artifact file for Flink Artifact in JAR or ZIP format.
	ArtifactFile *string `json:"artifactFile,omitempty" tf:"artifact_file,omitempty"`

	// Java class or alias for the Flink Artifact as provided by developer.
	// Java class or alias for the Flink Artifact as provided by developer.
	Class *string `json:"class,omitempty" tf:"class,omitempty"`

	// The cloud service provider that runs the Flink Artifact.
	// Cloud provider where the Flink Artifact archive is uploaded.
	Cloud *string `json:"cloud,omitempty" tf:"cloud,omitempty"`

	// Archive format of the Flink Artifact. Accepted values are: JAR, ZIP.
	// Archive format of the Flink Artifact (JAR or ZIP).
	ContentFormat *string `json:"contentFormat,omitempty" tf:"content_format,omitempty"`

	// Description of the Flink Artifact.
	// Description of the Flink Artifact.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The unique name of the Flink Artifact per cloud, region, environment scope.
	// The unique name of the Flink Artifact per cloud, region, environment scope.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Documentation link of the Flink Artifact.
	// Documentation link of the Flink Artifact.
	DocumentationLink *string `json:"documentationLink,omitempty" tf:"documentation_link,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	Environment []EnvironmentObservation `json:"environment,omitempty" tf:"environment,omitempty"`

	// The ID of the Environment that the Flink Artifact Pool belongs to, for example, env-abc123.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The kind of the Flink Artifact Pool, for example, FlinkArtifact.
	// The object this REST resource represents.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// The cloud service provider region that hosts the Flink Artifact.
	// The Cloud provider region the Flink Artifact archive is uploaded.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Runtime language of the Flink Artifact as Python or Java. Defaults to Java.
	// Runtime language of the Flink Artifact as Python or JAVA. The default runtime language is JAVA. Defaults to `JAVA`.
	RuntimeLanguage *string `json:"runtimeLanguage,omitempty" tf:"runtime_language,omitempty"`

	// List of versions for this Flink Artifact.
	Versions []VersionsObservation `json:"versions,omitempty" tf:"versions,omitempty"`
}

type ArtifactParameters struct {

	// The artifact file for Flink Artifact.
	// The artifact file for Flink Artifact in JAR or ZIP format.
	// +kubebuilder:validation:Optional
	ArtifactFile *string `json:"artifactFile,omitempty" tf:"artifact_file,omitempty"`

	// Java class or alias for the Flink Artifact as provided by developer.
	// Java class or alias for the Flink Artifact as provided by developer.
	// +kubebuilder:validation:Optional
	Class *string `json:"class,omitempty" tf:"class,omitempty"`

	// The cloud service provider that runs the Flink Artifact.
	// Cloud provider where the Flink Artifact archive is uploaded.
	// +kubebuilder:validation:Optional
	Cloud *string `json:"cloud,omitempty" tf:"cloud,omitempty"`

	// Archive format of the Flink Artifact. Accepted values are: JAR, ZIP.
	// Archive format of the Flink Artifact (JAR or ZIP).
	// +kubebuilder:validation:Optional
	ContentFormat *string `json:"contentFormat,omitempty" tf:"content_format,omitempty"`

	// Description of the Flink Artifact.
	// Description of the Flink Artifact.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The unique name of the Flink Artifact per cloud, region, environment scope.
	// The unique name of the Flink Artifact per cloud, region, environment scope.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Documentation link of the Flink Artifact.
	// Documentation link of the Flink Artifact.
	// +kubebuilder:validation:Optional
	DocumentationLink *string `json:"documentationLink,omitempty" tf:"documentation_link,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	// +kubebuilder:validation:Optional
	Environment []EnvironmentParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// The cloud service provider region that hosts the Flink Artifact.
	// The Cloud provider region the Flink Artifact archive is uploaded.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Runtime language of the Flink Artifact as Python or Java. Defaults to Java.
	// Runtime language of the Flink Artifact as Python or JAVA. The default runtime language is JAVA. Defaults to `JAVA`.
	// +kubebuilder:validation:Optional
	RuntimeLanguage *string `json:"runtimeLanguage,omitempty" tf:"runtime_language,omitempty"`
}

type EnvironmentInitParameters struct {

	// The ID of the Environment that the Flink Artifact Pool belongs to, for example, env-abc123.
	// The unique identifier for the environment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type EnvironmentObservation struct {

	// The ID of the Environment that the Flink Artifact Pool belongs to, for example, env-abc123.
	// The unique identifier for the environment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type EnvironmentParameters struct {

	// The ID of the Environment that the Flink Artifact Pool belongs to, for example, env-abc123.
	// The unique identifier for the environment.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type VersionsInitParameters struct {
}

type VersionsObservation struct {
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type VersionsParameters struct {
}

// ArtifactSpec defines the desired state of Artifact
type ArtifactSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ArtifactParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ArtifactInitParameters `json:"initProvider,omitempty"`
}

// ArtifactStatus defines the observed state of Artifact.
type ArtifactStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ArtifactObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Artifact is the Schema for the Artifacts API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,confluent}
type Artifact struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cloud) || (has(self.initProvider) && has(self.initProvider.cloud))",message="spec.forProvider.cloud is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.environment) || (has(self.initProvider) && has(self.initProvider.environment))",message="spec.forProvider.environment is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	Spec   ArtifactSpec   `json:"spec"`
	Status ArtifactStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ArtifactList contains a list of Artifacts
type ArtifactList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Artifact `json:"items"`
}

// Repository type metadata.
var (
	Artifact_Kind             = "Artifact"
	Artifact_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Artifact_Kind}.String()
	Artifact_KindAPIVersion   = Artifact_Kind + "." + CRDGroupVersion.String()
	Artifact_GroupVersionKind = CRDGroupVersion.WithKind(Artifact_Kind)
)

func init() {
	SchemeBuilder.Register(&Artifact{}, &ArtifactList{})
}
