// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ComputePoolEnvironmentInitParameters struct {

	// The ID of the Environment that the Flink Compute Pool belongs to, for example, env-abc123.
	// The unique identifier for the environment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ComputePoolEnvironmentObservation struct {

	// The ID of the Environment that the Flink Compute Pool belongs to, for example, env-abc123.
	// The unique identifier for the environment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ComputePoolEnvironmentParameters struct {

	// The ID of the Environment that the Flink Compute Pool belongs to, for example, env-abc123.
	// The unique identifier for the environment.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type ComputePoolInitParameters struct {

	// The cloud service provider that runs the Flink Compute Pool.
	// The cloud service provider that runs the compute pool.
	Cloud *string `json:"cloud,omitempty" tf:"cloud,omitempty"`

	// The name of the Flink Compute Pool.
	// The name of the Flink compute pool.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	Environment []ComputePoolEnvironmentInitParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// Maximum number of Confluent Flink Units (CFUs) that the Flink compute pool should auto-scale to. The accepted values are: 5, 10, 20, 30, 40 and 50.
	// Maximum number of Confluent Flink Units (CFUs) that the Flink compute pool should auto-scale to.
	MaxCfu *float64 `json:"maxCfu,omitempty" tf:"max_cfu,omitempty"`

	// The cloud service provider region that hosts the Flink Compute Pool.
	// The cloud service provider region that hosts the Flink compute pool.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type ComputePoolObservation struct {

	// The API Version of the schema version of the Flink Compute Pool, for example, fcpm/v2.
	APIVersion *string `json:"apiVersion,omitempty" tf:"api_version,omitempty"`

	// The cloud service provider that runs the Flink Compute Pool.
	// The cloud service provider that runs the compute pool.
	Cloud *string `json:"cloud,omitempty" tf:"cloud,omitempty"`

	// The name of the Flink Compute Pool.
	// The name of the Flink compute pool.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	Environment []ComputePoolEnvironmentObservation `json:"environment,omitempty" tf:"environment,omitempty"`

	// The ID of the Environment that the Flink Compute Pool belongs to, for example, env-abc123.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The kind of the Flink Compute Pool, for example, ComputePool.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// Maximum number of Confluent Flink Units (CFUs) that the Flink compute pool should auto-scale to. The accepted values are: 5, 10, 20, 30, 40 and 50.
	// Maximum number of Confluent Flink Units (CFUs) that the Flink compute pool should auto-scale to.
	MaxCfu *float64 `json:"maxCfu,omitempty" tf:"max_cfu,omitempty"`

	// The cloud service provider region that hosts the Flink Compute Pool.
	// The cloud service provider region that hosts the Flink compute pool.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The Confluent Resource Name of the Flink Compute Pool.
	// The Confluent Resource Name of the Flink compute pool.
	ResourceName *string `json:"resourceName,omitempty" tf:"resource_name,omitempty"`
}

type ComputePoolParameters struct {

	// The cloud service provider that runs the Flink Compute Pool.
	// The cloud service provider that runs the compute pool.
	// +kubebuilder:validation:Optional
	Cloud *string `json:"cloud,omitempty" tf:"cloud,omitempty"`

	// The name of the Flink Compute Pool.
	// The name of the Flink compute pool.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	// +kubebuilder:validation:Optional
	Environment []ComputePoolEnvironmentParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// Maximum number of Confluent Flink Units (CFUs) that the Flink compute pool should auto-scale to. The accepted values are: 5, 10, 20, 30, 40 and 50.
	// Maximum number of Confluent Flink Units (CFUs) that the Flink compute pool should auto-scale to.
	// +kubebuilder:validation:Optional
	MaxCfu *float64 `json:"maxCfu,omitempty" tf:"max_cfu,omitempty"`

	// The cloud service provider region that hosts the Flink Compute Pool.
	// The cloud service provider region that hosts the Flink compute pool.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

// ComputePoolSpec defines the desired state of ComputePool
type ComputePoolSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ComputePoolParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ComputePoolInitParameters `json:"initProvider,omitempty"`
}

// ComputePoolStatus defines the observed state of ComputePool.
type ComputePoolStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ComputePoolObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// ComputePool is the Schema for the ComputePools API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,confluent}
type ComputePool struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cloud) || (has(self.initProvider) && has(self.initProvider.cloud))",message="spec.forProvider.cloud is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.environment) || (has(self.initProvider) && has(self.initProvider.environment))",message="spec.forProvider.environment is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	Spec   ComputePoolSpec   `json:"spec"`
	Status ComputePoolStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ComputePoolList contains a list of ComputePools
type ComputePoolList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ComputePool `json:"items"`
}

// Repository type metadata.
var (
	ComputePool_Kind             = "ComputePool"
	ComputePool_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ComputePool_Kind}.String()
	ComputePool_KindAPIVersion   = ComputePool_Kind + "." + CRDGroupVersion.String()
	ComputePool_GroupVersionKind = CRDGroupVersion.WithKind(ComputePool_Kind)
)

func init() {
	SchemeBuilder.Register(&ComputePool{}, &ComputePoolList{})
}
