// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CredentialsInitParameters struct {
}

type CredentialsObservation struct {
}

type CredentialsParameters struct {

	// The Flink API Key.
	// The Cluster API Key for your Confluent Cloud cluster.
	// +kubebuilder:validation:Required
	KeySecretRef v1.SecretKeySelector `json:"keySecretRef" tf:"-"`

	// The Flink API Secret.
	// The Cluster API Secret for your Confluent Cloud cluster.
	// +kubebuilder:validation:Required
	SecretSecretRef v1.SecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type OrganizationInitParameters struct {

	// The ID of the Organization, for example, 1111aaaa-11aa-11aa-11aa-111111aaaaaa.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type OrganizationObservation struct {

	// The ID of the Organization, for example, 1111aaaa-11aa-11aa-11aa-111111aaaaaa.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type OrganizationParameters struct {

	// The ID of the Organization, for example, 1111aaaa-11aa-11aa-11aa-111111aaaaaa.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type PrincipalInitParameters struct {

	// The ID of the Organization, for example, 1111aaaa-11aa-11aa-11aa-111111aaaaaa.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type PrincipalObservation struct {

	// The ID of the Organization, for example, 1111aaaa-11aa-11aa-11aa-111111aaaaaa.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type PrincipalParameters struct {

	// The ID of the Organization, for example, 1111aaaa-11aa-11aa-11aa-111111aaaaaa.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type StatementComputePoolInitParameters struct {
}

type StatementComputePoolObservation struct {

	// The ID of the Organization, for example, 1111aaaa-11aa-11aa-11aa-111111aaaaaa.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type StatementComputePoolParameters struct {

	// The ID of the Organization, for example, 1111aaaa-11aa-11aa-11aa-111111aaaaaa.
	// +crossplane:generate:reference:type=ComputePool
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Reference to a ComputePool to populate id.
	// +kubebuilder:validation:Optional
	IDRef *v1.Reference `json:"idRef,omitempty" tf:"-"`

	// Selector for a ComputePool to populate id.
	// +kubebuilder:validation:Optional
	IDSelector *v1.Selector `json:"idSelector,omitempty" tf:"-"`
}

type StatementEnvironmentInitParameters struct {

	// The ID of the Organization, for example, 1111aaaa-11aa-11aa-11aa-111111aaaaaa.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type StatementEnvironmentObservation struct {

	// The ID of the Organization, for example, 1111aaaa-11aa-11aa-11aa-111111aaaaaa.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type StatementEnvironmentParameters struct {

	// The ID of the Organization, for example, 1111aaaa-11aa-11aa-11aa-111111aaaaaa.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type StatementInitParameters struct {

	// supports the following:
	ComputePool []StatementComputePoolInitParameters `json:"computePool,omitempty" tf:"compute_pool,omitempty"`

	// supports the following:
	// The Cluster API Credentials.
	Credentials []CredentialsInitParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// supports the following:
	Environment []StatementEnvironmentInitParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// supports the following:
	Organization []OrganizationInitParameters `json:"organization,omitempty" tf:"organization,omitempty"`

	// supports the following:
	Principal []PrincipalInitParameters `json:"principal,omitempty" tf:"principal,omitempty"`

	// The custom topic settings to set:
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`

	// The REST endpoint of the Flink region, for example, https://flink.us-east-1.aws.confluent.cloud).
	// The REST endpoint of the Flink Compute Pool cluster, for example, `https://flink.us-east-1.aws.confluent.cloud/sql/v1/organizations/1111aaaa-11aa-11aa-11aa-111111aaaaaa/environments/env-abc123`).
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`

	// The raw SQL text statement, for example, SELECT CURRENT_TIMESTAMP;.
	// The raw SQL text of the Statement.
	Statement *string `json:"statement,omitempty" tf:"statement,omitempty"`

	// The ID of the Flink Statement, for example, cfeab4fe-b62c-49bd-9e99-51cc98c77a67.
	// The unique identifier of the Statement.
	StatementName *string `json:"statementName,omitempty" tf:"statement_name,omitempty"`

	// The boolean flag is used to indicate the statement's running status and to control whether the Flink Statement should be stopped or resumed. Defaults to false. Update it to true to stop the statement. Subsequently update it to false to resume the statement.
	// Indicates whether the statement should be stopped.
	Stopped *bool `json:"stopped,omitempty" tf:"stopped,omitempty"`
}

type StatementObservation struct {

	// supports the following:
	ComputePool []StatementComputePoolObservation `json:"computePool,omitempty" tf:"compute_pool,omitempty"`

	// supports the following:
	// The Cluster API Credentials.
	Credentials []CredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// supports the following:
	Environment []StatementEnvironmentObservation `json:"environment,omitempty" tf:"environment,omitempty"`

	// The ID of the Organization, for example, 1111aaaa-11aa-11aa-11aa-111111aaaaaa.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The last Kafka offsets that a statement has processed. Represented by a mapping from Kafka topic to a string representation of partitions mapped to offsets. For example,
	// The last Kafka offsets that a statement has processed. Represented by a mapping from Kafka topic to a string representation of partitions mapped to offsets.
	LatestOffsets map[string]*string `json:"latestOffsets,omitempty" tf:"latest_offsets,omitempty"`

	// The date and time at which the Kafka topic offsets were added to the statement status. It is represented in RFC3339 format and is in UTC. For example, 2023-03-31T00:00:00-00:00.
	// The date and time at which the Kafka topic offsets were added to the statement status. It is represented in RFC3339 format and is in UTC.
	LatestOffsetsTimestamp *string `json:"latestOffsetsTimestamp,omitempty" tf:"latest_offsets_timestamp,omitempty"`

	// supports the following:
	Organization []OrganizationObservation `json:"organization,omitempty" tf:"organization,omitempty"`

	// supports the following:
	Principal []PrincipalObservation `json:"principal,omitempty" tf:"principal,omitempty"`

	// The custom topic settings to set:
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`

	// The REST endpoint of the Flink region, for example, https://flink.us-east-1.aws.confluent.cloud).
	// The REST endpoint of the Flink Compute Pool cluster, for example, `https://flink.us-east-1.aws.confluent.cloud/sql/v1/organizations/1111aaaa-11aa-11aa-11aa-111111aaaaaa/environments/env-abc123`).
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`

	// The raw SQL text statement, for example, SELECT CURRENT_TIMESTAMP;.
	// The raw SQL text of the Statement.
	Statement *string `json:"statement,omitempty" tf:"statement,omitempty"`

	// The ID of the Flink Statement, for example, cfeab4fe-b62c-49bd-9e99-51cc98c77a67.
	// The unique identifier of the Statement.
	StatementName *string `json:"statementName,omitempty" tf:"statement_name,omitempty"`

	// The boolean flag is used to indicate the statement's running status and to control whether the Flink Statement should be stopped or resumed. Defaults to false. Update it to true to stop the statement. Subsequently update it to false to resume the statement.
	// Indicates whether the statement should be stopped.
	Stopped *bool `json:"stopped,omitempty" tf:"stopped,omitempty"`
}

type StatementParameters struct {

	// supports the following:
	// +kubebuilder:validation:Optional
	ComputePool []StatementComputePoolParameters `json:"computePool,omitempty" tf:"compute_pool,omitempty"`

	// supports the following:
	// The Cluster API Credentials.
	// +kubebuilder:validation:Optional
	Credentials []CredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// supports the following:
	// +kubebuilder:validation:Optional
	Environment []StatementEnvironmentParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// supports the following:
	// +kubebuilder:validation:Optional
	Organization []OrganizationParameters `json:"organization,omitempty" tf:"organization,omitempty"`

	// supports the following:
	// +kubebuilder:validation:Optional
	Principal []PrincipalParameters `json:"principal,omitempty" tf:"principal,omitempty"`

	// The custom topic settings to set:
	// +kubebuilder:validation:Optional
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`

	// Block for sensitive statement properties:
	// +kubebuilder:validation:Optional
	PropertiesSensitiveSecretRef *v1.SecretReference `json:"propertiesSensitiveSecretRef,omitempty" tf:"-"`

	// The REST endpoint of the Flink region, for example, https://flink.us-east-1.aws.confluent.cloud).
	// The REST endpoint of the Flink Compute Pool cluster, for example, `https://flink.us-east-1.aws.confluent.cloud/sql/v1/organizations/1111aaaa-11aa-11aa-11aa-111111aaaaaa/environments/env-abc123`).
	// +kubebuilder:validation:Optional
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`

	// The raw SQL text statement, for example, SELECT CURRENT_TIMESTAMP;.
	// The raw SQL text of the Statement.
	// +kubebuilder:validation:Optional
	Statement *string `json:"statement,omitempty" tf:"statement,omitempty"`

	// The ID of the Flink Statement, for example, cfeab4fe-b62c-49bd-9e99-51cc98c77a67.
	// The unique identifier of the Statement.
	// +kubebuilder:validation:Optional
	StatementName *string `json:"statementName,omitempty" tf:"statement_name,omitempty"`

	// The boolean flag is used to indicate the statement's running status and to control whether the Flink Statement should be stopped or resumed. Defaults to false. Update it to true to stop the statement. Subsequently update it to false to resume the statement.
	// Indicates whether the statement should be stopped.
	// +kubebuilder:validation:Optional
	Stopped *bool `json:"stopped,omitempty" tf:"stopped,omitempty"`
}

// StatementSpec defines the desired state of Statement
type StatementSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     StatementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider StatementInitParameters `json:"initProvider,omitempty"`
}

// StatementStatus defines the observed state of Statement.
type StatementStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        StatementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Statement is the Schema for the Statements API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,confluent}
type Statement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.statement) || (has(self.initProvider) && has(self.initProvider.statement))",message="spec.forProvider.statement is a required parameter"
	Spec   StatementSpec   `json:"spec"`
	Status StatementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// StatementList contains a list of Statements
type StatementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Statement `json:"items"`
}

// Repository type metadata.
var (
	Statement_Kind             = "Statement"
	Statement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Statement_Kind}.String()
	Statement_KindAPIVersion   = Statement_Kind + "." + CRDGroupVersion.String()
	Statement_GroupVersionKind = CRDGroupVersion.WithKind(Statement_Kind)
)

func init() {
	SchemeBuilder.Register(&Statement{}, &StatementList{})
}
